import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {useEffect,useMemo,useRef} from 'react';
import * as THREE from 'three';
import type {JourneyMotion} from './journeyData';
const PALETTES=[['#213e4e','#719fae','#c5ddd7'],['#45493e','#999e84','#b85439'],['#35442d','#9fab57','#d36342'],['#273c30','#94a384','#a9c2d9'],['#3d3029','#a59376','#d4bea0']];
function FilmCamera({position,angle=0}:{position:[number,number,number];angle?:number}){return <group position={position} rotation={[0,angle,0]}><mesh position={[0,1.7,0]}><boxGeometry args={[1.8,1.1,1.1]}/><meshStandardMaterial color="#657c79" roughness={.86} flatShading/></mesh><mesh position={[0,1.75,.83]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.43,.55,.65,8]}/><meshStandardMaterial color="#172e34" roughness={.5}/></mesh>{[-.53,.53].map(x=><mesh key={x} position={[x,2.5,0]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.62,.62,.3,8]}/><meshStandardMaterial color="#b6c3b6" roughness={.7} flatShading/></mesh>)}{[-1,0,1].map(i=><mesh key={i} position={[i*.32,.7,0]} rotation={[i*.25,0,i*.3]}><boxGeometry args={[.12,1.6,.12]}/><meshStandardMaterial color="#9cab9c" roughness={1}/></mesh>)}</group>}
function Monitor({position,rotation=0}:{position:[number,number,number];rotation?:number}){return <group position={position} rotation={[0,rotation,0]}><mesh position={[0,1,0]}><boxGeometry args={[2.5,1.9,1.25]}/><meshStandardMaterial color="#bac0a6" roughness={.8} flatShading/></mesh><mesh position={[0,1,.65]}><planeGeometry args={[2.12,1.48]}/><meshStandardMaterial color="#203845" emissive="#214455" emissiveIntensity={.35} roughness={.65}/></mesh><mesh position={[0,-.08,0]}><cylinderGeometry args={[.38,.62,.55,6]}/><meshStandardMaterial color="#898e7d" roughness={1}/></mesh><mesh position={[0,-.42,.1]}><boxGeometry args={[1.4,.17,1.1]}/><meshStandardMaterial color="#929b85" roughness={1}/></mesh></group>}
function Scenery({index}:{index:number}){const theme=index%5,colors=PALETTES[theme];return <>
 <mesh position={[0,-3.35,-8]} rotation={[0,.13,0]}><cylinderGeometry args={[11,8,2.5,6]}/><meshStandardMaterial color={colors[0]} flatShading roughness={1}/></mesh>
 <mesh position={[0,-1.99,-8]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[3.6,25]}/><meshStandardMaterial color={colors[1]} transparent opacity={.18} roughness={1}/></mesh>
 {[-1,1].map(side=><group key={side}>{[0,1,2].map(i=><mesh key={i} position={[side*(5.7+i*.55),-1.3+i*.5,-2-i*6]} rotation={[0,side*.18,0]}><boxGeometry args={[2.1,1.4+i,3.3]}/><meshStandardMaterial color={i%2?colors[0]:colors[1]} flatShading roughness={.9}/></mesh>)}</group>)}
 <mesh position={[0,2.7,-18]} rotation={[0,0,Math.PI/4]}><torusGeometry args={[7.2,.13,4,4]}/><meshStandardMaterial color={colors[2]} emissive={colors[2]} emissiveIntensity={.2} roughness={.8}/></mesh>
 {theme===0?<><mesh position={[-5,1,-3]} rotation={[.4,.2,.4]}><icosahedronGeometry args={[1.35,0]}/><meshPhysicalMaterial color={colors[2]} transparent opacity={.65} roughness={.25} metalness={0} flatShading/></mesh><FilmCamera position={[6,-1.4,-8]} angle={-.5}/></>:theme===1?<><FilmCamera position={[-6,-1.5,-4]} angle={.5}/><mesh position={[6,1,-7]} rotation={[0,.2,-.1]}><boxGeometry args={[1.7,6,1.7]}/><meshStandardMaterial color={colors[2]} roughness={1} flatShading/></mesh></>:theme===2?<>{[0,1,2].map(i=><mesh key={i} position={[-6+i*6,2+i%2,-9]} rotation={[0,.2,i*.5-.3]}><boxGeometry args={[1.5,2.6,.18]}/><meshStandardMaterial color={i%2?colors[2]:colors[1]} flatShading roughness={.9}/></mesh>)}</>:theme===3?<><Monitor position={[-6,-.5,-4]} rotation={.55}/><Monitor position={[6,-.6,-13]} rotation={-.5}/></>:<><FilmCamera position={[5,-1.2,-10]} angle={-.4}/><mesh position={[-6,.5,-4]} rotation={[.2,.1,.3]}><torusGeometry args={[1.4,.25,5,8]}/><meshStandardMaterial color={colors[2]} roughness={.8}/></mesh></>}
 {Array.from({length:8},(_,i)=><mesh key={i} position={[(i%2?1:-1)*(8+(i%3)*.9),-1.8,-i*3.8]} rotation={[i*.16,i*.7,i*.3]}><dodecahedronGeometry args={[.5+(i%3)*.3,0]}/><meshStandardMaterial color={i%2?colors[1]:colors[0]} roughness={1} flatShading/></mesh>)}
 </>}
function Flight({motion}:{motion:JourneyMotion}){
 const {camera,invalidate,setDpr}=useThree(),zones=useRef<(THREE.Group|null)[]>([]),look=useMemo(()=>new THREE.Vector3(),[]);
 useEffect(()=>{motion.invalidate=invalidate;invalidate();return()=>{motion.invalidate=()=>{}}},[motion,invalidate]);
 const oldLow=useRef(motion.low);
 useFrame(()=>{const p=motion.position,step=Math.floor(p);camera.position.set(Math.sin(p*.72)*1.7+motion.pointerX*.45,3.5+Math.cos(p*.55)*.5+motion.pointerY*.3,12-p*26);look.set(Math.sin((p+.5)*.72)*1.3,1, camera.position.z-30);camera.lookAt(look);zones.current.forEach((zone,i)=>{if(!zone)return;const nearest=i+Math.round((step-i)/5)*5;zone.position.set(Math.sin(nearest*.72)*1.7,0,-nearest*26);zone.visible=nearest>=step-1&&nearest<=step+2});if(oldLow.current!==motion.low){oldLow.current=motion.low;setDpr(motion.low?1:Math.min(devicePixelRatio,1.5))}});
 return <><ambientLight intensity={1.15}/><hemisphereLight args={['#dce9ec','#283c32',1.8]}/><directionalLight position={[-5,12,6]} intensity={2.5} color="#e8e3d3"/>{[0,1,2,3,4].map(i=><group key={i} ref={el=>{zones.current[i]=el}}><Scenery index={i}/></group>)}</>
}
export default function JourneyScene({motion,onFailure}:{motion:JourneyMotion;onDiscover:()=>void;onFailure:()=>void}){return <Canvas className="journey-canvas" frameloop="demand" dpr={motion.low?1:[1,1.5]} camera={{fov:52,position:[0,4,12],near:.1,far:125}} gl={{antialias:true,alpha:true,powerPreference:'default'}} fallback={null} onCreated={({gl})=>{gl.setClearColor(0,0);gl.domElement.addEventListener('webglcontextlost',onFailure,{once:true})}}><Flight motion={motion}/></Canvas>}
