import {Canvas,useFrame,useThree,type ThreeEvent} from '@react-three/fiber';
import {useEffect,useMemo,useRef} from 'react';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {wrap,type JourneyMotion} from './journeyData';
function Environment(){const {gl,scene,invalidate}=useThree();useEffect(()=>{const room=new RoomEnvironment(),generator=new THREE.PMREMGenerator(gl),target=generator.fromScene(room,.05);scene.environment=target.texture;invalidate();return()=>{scene.environment=null;target.dispose();room.dispose();generator.dispose()}},[gl,scene,invalidate]);return null}
function Objects({motion,onDiscover}:{motion:JourneyMotion;onDiscover:()=>void}){
 const {camera,invalidate,setDpr}=useThree(),groups=useRef<(THREE.Group|null)[]>([]);
 const path=useMemo(()=>new THREE.CatmullRomCurve3([new THREE.Vector3(0,1,15),new THREE.Vector3(3,2,14),new THREE.Vector3(-2,3,13),new THREE.Vector3(-3,-.5,17),new THREE.Vector3(2,1.5,14)],true,'catmullrom',.35),[]),pt=useMemo(()=>new THREE.Vector3(),[]);
 useEffect(()=>{motion.invalidate=invalidate;invalidate();return()=>{motion.invalidate=()=>{}}},[motion,invalidate]);
 const oldLow=useRef(motion.low);
 useFrame(()=>{const p=wrap(motion.position),a=Math.floor(p),b=(a+1)%5,t=THREE.MathUtils.smoothstep(p-a,.48,1);path.getPointAt(p/5,pt);camera.position.copy(pt);camera.position.x+=motion.pointerX*.45;camera.position.y+=motion.pointerY*.25;camera.lookAt(0,0,0);groups.current.forEach((group,i)=>{if(!group)return;const w=i===a?1-t:i===b?t:0;group.visible=w>.015;group.scale.setScalar(Math.max(.01,w));group.rotation.y=motion.pointerX*.1+Math.sin(motion.time*.2+i)*.045;group.position.y=Math.sin(motion.time*.35+i)*.13});if(oldLow.current!==motion.low){oldLow.current=motion.low;setDpr(motion.low?1:Math.min(devicePixelRatio,1.75))}});
 function over(e:ThreeEvent<PointerEvent>){e.stopPropagation();document.body.style.cursor='pointer'}
 const click=(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();onDiscover()},out=()=>{document.body.style.cursor='auto'};
 return <><ambientLight intensity={.75}/><directionalLight position={[-5,8,8]} intensity={3.5} color="#f3e9d9"/><pointLight position={[8,2,5]} intensity={55} color="#88b7f8"/>
 <group ref={el=>{groups.current[0]=el}}><mesh position={[-5,-1,1]} rotation={[.3,.5,.4]} onClick={click} onPointerOver={over} onPointerOut={out}><icosahedronGeometry args={[2.05,0]}/><meshPhysicalMaterial color="#8eafc5" roughness={.1} metalness={.15} transmission={motion.low?0:.7} thickness={1.5} ior={1.35} transparent opacity={.8} clearcoat={1}/></mesh><mesh position={[6.5,3,-3]} rotation={[.5,0,.3]}><torusGeometry args={[1.2,.12,6,28]}/><meshStandardMaterial color="#d7e6ee" metalness={.65} roughness={.22}/></mesh>{[0,1,2,3,4,5].map(i=><mesh key={i} position={[-9+i*3.5,-5,-4]} rotation={[0,0,i*.08]}><boxGeometry args={[1.1,4+i%3,1.1]}/><meshStandardMaterial color="#223748" roughness={.5} metalness={.15}/></mesh>)}</group>
 <group ref={el=>{groups.current[1]=el}}>{Array.from({length:8},(_,i)=><mesh key={i} position={[-10+i*3,-2.8,-2-(i%3)]} rotation={[.06,i*.08,-.03]}><boxGeometry args={[1.5,3+(i%4)*1.4,2]}/><meshStandardMaterial color={i===2?'#9b261d':'#9f9c94'} roughness={.95}/></mesh>)}<mesh position={[-5,2,0]} rotation={[0,0,-.08]} onClick={click} onPointerOver={over} onPointerOut={out}><boxGeometry args={[3.5,.7,1]}/><meshStandardMaterial color="#ac2d24" roughness={.7}/></mesh></group>
 <group ref={el=>{groups.current[2]=el}}>{[0,1,2,3,4,5].map(i=><mesh key={i} position={[-8+i*3,-3+Math.sin(i)*2,-1-i%2]} rotation={[.3,.2,i*.4]}><boxGeometry args={[2.7,3.6,.09]}/><meshStandardMaterial color={i%3===0?'#d14430':i%3===1?'#d4d3c6':'#1228b9'} roughness={1}/></mesh>)}</group>
 <group ref={el=>{groups.current[3]=el}}>{Array.from({length:10},(_,i)=><mesh key={i} position={[-10+i*2.3,-4+(i%3),-3-(i%2)*2]} rotation={[.1,.25,i*.03]}><boxGeometry args={[1.4,2.6+(i%4),.3]}/><meshStandardMaterial color={i%2?'#485f4c':'#232e25'} roughness={.85}/></mesh>)}<mesh position={[-5,0,0]} rotation={[.1,.1,-.16]} onClick={click} onPointerOver={over} onPointerOut={out}><boxGeometry args={[2.7,2.1,.18]}/><meshStandardMaterial color="#adada4" roughness={.45}/></mesh></group>
 <group ref={el=>{groups.current[4]=el}}>{[0,1,2,3,4,5,6,7].map(i=><mesh key={i} position={[Math.cos(i*.8)*8,Math.sin(i*.8)*4,-3]} rotation={[0,0,i*.15]}><boxGeometry args={[2.1,.08,.7]}/><meshStandardMaterial color="#9b8770" roughness={.45} metalness={.4}/></mesh>)}<mesh position={[-5,-1,2]} rotation={[.15,.4,.2]} onClick={click} onPointerOver={over} onPointerOut={out}><torusGeometry args={[1.6,.1,4,4]}/><meshStandardMaterial color="#e1d7c2" metalness={.35} roughness={.4}/></mesh></group></>;
}
export default function JourneyScene({motion,onDiscover,onFailure}:{motion:JourneyMotion;onDiscover:()=>void;onFailure:()=>void}){return <Canvas className="journey-canvas" frameloop="demand" dpr={motion.low?1:[1,1.75]} camera={{fov:46,position:[0,1,15],near:.1,far:100}} gl={{antialias:true,alpha:true,powerPreference:'default'}} fallback={null} onCreated={({gl})=>{gl.setClearColor(0x000000,0);gl.domElement.addEventListener('webglcontextlost',onFailure,{once:true})}}><Environment/><Objects motion={motion} onDiscover={onDiscover}/></Canvas>}
