import {Component,Suspense,lazy,useEffect,useMemo,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {asset,type Project} from './content';
import {worlds,wrap,type JourneyMotion} from './journeyData';
import JourneyPlayer from './JourneyPlayer';
import KineticName from './KineticName';
import './journey.css';
const Scene=lazy(()=>import('./JourneyScene'));
class GeometryBoundary extends Component<{children:ReactNode;onFailure:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}componentDidCatch(){this.props.onFailure()}render(){return this.state.failed?null:this.props.children}}
type Props={projects:Project[];onProject:(p:Project)=>void;onIndex:()=>void;paused:boolean;reduced:boolean};
const ease=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
function Discovery({project,kind,onReveal}:{project:Project;kind:string;onReveal:(p:Project)=>void}){
 const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>()=>clearTimeout(timer.current),[]);
 return <button className={'discovery discovery-'+kind} aria-label={'Discover '+project.title} onPointerEnter={e=>{if(e.pointerType==='mouse')timer.current=setTimeout(()=>onReveal(project),600)}} onPointerLeave={()=>clearTimeout(timer.current)} onClick={()=>onReveal(project)}><svg viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.2">{kind==='aperture'?<><circle cx="16" cy="16" r="12"/><path d="m16 4 8 16H8zm10 5-18 4m18 10-16-9M16 28l8-15"/></>:kind==='film'?<><rect x="4" y="9" width="24" height="18" rx="1"/><path d="m4 9 22-6 2 6M9 8l3-5m5 3 3-4M4 15h24m-14 4 7 4-7 4z"/></>:kind==='ticket'?<><path d="M3 9h26v5a3 3 0 0 0 0 6v5H3v-5a3 3 0 0 0 0-6z"/><path d="M10 9v3m0 3v3m0 3v4m7-10h7m-7 5h5"/></>:kind==='window'?<><rect x="3" y="5" width="26" height="22"/><path d="M3 11h26m-5-3h2M9 16l4 3-4 3m7 0h7"/></>:<><rect x="6" y="3" width="20" height="26"/><path d="M9 9h14v14H9zM10 6h3m6 0h3m-12 20h3m6 0h3"/></>}</svg></button>;
}
function ImageTile({p,index,onReveal}:{p:Project;index:number;onReveal:(p:Project)=>void}){return <button className={'world-image image-'+index} onClick={()=>onReveal(p)} aria-label={'Open '+p.title}>{p.poster&&<img src={asset(p.poster)} alt="" decoding="async"/>}<span>{p.title.split(' | ')[0].split(' (Official')[0]}</span></button>}
function World({index,projects,onReveal}:{index:number;projects:Project[];onReveal:(p:Project)=>void}){
 const w=worlds[index],cards=w.cards.map(id=>projects.find(p=>p.id===id)).filter(Boolean) as Project[];
 return <section className={'journey-world world-'+w.kind} data-world-index={index} aria-label={w.name}>
 {index===0&&<><div className="glass-name"><KineticName/></div><div className="glass-orbit"/><div className="glass-rule"/></>}
 {index===1&&<><div className="mass-number" aria-hidden="true">02</div><div className="mass-rule"/><span className="mass-caption">TRAILERS / FILM</span></>}
 {index===2&&<><div className="cut-word" aria-hidden="true">CUT.</div><span className="cut-stamp">LIVE / LOUD</span><div className="cut-reg" aria-hidden="true">+</div></>}
 {index===3&&<><div className="desktop-wallpaper" style={{backgroundImage:`url(${asset(cards[2]?.poster)})`}}/><div className="desktop-icon"><span>▣</span><span>My work</span></div><div className="desktop-clock">PD / 1998</div></>}
 {index===4&&<><div className="afterimage-type">After<br/><em>image.</em></div><div className="contact-rule"/></>}
 <div className="world-images">{cards.map((p,i)=><ImageTile key={p.id} p={p} index={i} onReveal={onReveal}/>)}</div></section>;
}
export default function Universe({projects,onProject,onIndex,paused,reduced}:Props){
 const root=useRef<HTMLDivElement>(null),scroll=useRef<HTMLDivElement>(null),screen=useRef<HTMLDivElement>(null);
 const [chapter,setChapter]=useState(0),[pair,setPair]=useState([0,1]),[override,setOverride]=useState<Project|null>(null),[muted,setMuted]=useState(true),[playing,setPlaying]=useState(true),[low,setLow]=useState(false),[graphics,setGraphics]=useState(true),[saveData,setSaveData]=useState(false);
 const motion=useMemo<JourneyMotion>(()=>({position:0,target:0,pointerX:0,pointerY:0,velocity:0,time:0,active:true,low:false,reduced:false,invalidate:()=>{}}),[]);
 const settings=useRef({paused,reduced});settings.current={paused,reduced};motion.low=low;motion.reduced=reduced;motion.active=!paused;
 const wakeRef=useRef<()=>void>(()=>{}),navigateRef=useRef<(index:number)=>void>(()=>{}),currentChapter=useRef(0),jumping=useRef(false);
 useEffect(()=>{const n=navigator as Navigator&{connection?:{saveData?:boolean};deviceMemory?:number};setSaveData(!!n.connection?.saveData);setLow(!!n.connection?.saveData||(n.deviceMemory||8)<=4||navigator.hardwareConcurrency<=4)},[]);
 useEffect(()=>{
 const el=scroll.current,outer=root.current;if(!el||!outer)return;let unit=1,lastRaw=0,raf=0,last=performance.now(),introUntil=last+1800,px=0,py=0,pairKey=0;
 function resize(){unit=el!.clientHeight*1.4;outer!.style.setProperty('--scroll-unit',unit+'px');jumping.current=true;el!.scrollTop=(wrap(motion.position)+1)*unit;lastRaw=wrap(motion.position);jumping.current=false;wake()}
 function update(t:number){raf=0;if(settings.current.paused||document.hidden)return;const dt=Math.min((t-last)/1000,.04)||.016;last=t;const old=motion.position;motion.position+=(motion.target-motion.position)*(settings.current.reduced?1:1-Math.exp(-9*dt));if(Math.abs(motion.target-motion.position)<.00015)motion.position=motion.target;motion.velocity=(motion.position-old)/dt;motion.time=t/1000;motion.pointerX+=(px-motion.pointerX)*(1-Math.exp(-7*dt));motion.pointerY+=(py-motion.pointerY)*(1-Math.exp(-7*dt));
 const phase=wrap(motion.position),a=Math.floor(phase),b=(a+1)%5,blend=ease(.52,1,phase-a);if(a!==pairKey){pairKey=a;setPair([a,b])}const active=blend>.52?b:a;if(currentChapter.current!==active){currentChapter.current=active;setChapter(active);setOverride(null)}outer!.style.setProperty('--pointer-x',String(motion.pointerX));outer!.style.setProperty('--pointer-y',String(motion.pointerY));
 outer!.querySelectorAll<HTMLElement>('.journey-world').forEach(layer=>{const i=Number(layer.dataset.worldIndex),weight=i===a?1-blend:i===b?blend:0;layer.style.opacity=String(weight);layer.style.pointerEvents=weight>.52?'auto':'none';layer.inert=weight<.52;layer.style.setProperty('--travel',String(settings.current.reduced?0:i===a?-blend:1-blend))});
 if(screen.current){const xs=[62,62,53,61,63],ys=[48,48,48,45,45],mobile=el!.clientWidth<700,x=mobile?50:xs[a]+(xs[b]-xs[a])*blend,y=mobile?45:ys[a]+(ys[b]-ys[a])*blend;screen.current.style.left=x+'%';screen.current.style.top=y+'%';screen.current.style.setProperty('--film-ry',`${settings.current.reduced?0:Math.sin(phase*Math.PI*2/5)*3+motion.pointerX*1.3}deg`);screen.current.style.setProperty('--film-scale',String(settings.current.reduced?1:1+Math.sin(phase*Math.PI*2/5)*.035));screen.current.style.setProperty('--film-rz',`${settings.current.reduced?0:Math.sin(phase*Math.PI*2/5)*1.3}deg`)}motion.invalidate();if(Math.abs(motion.target-motion.position)>.00015||Math.abs(motion.pointerX-px)+Math.abs(motion.pointerY-py)>.002||t<introUntil)raf=requestAnimationFrame(update)}
 function wake(){if(!raf){last=performance.now();raf=requestAnimationFrame(update)}}wakeRef.current=wake;navigateRef.current=(index:number)=>{const dest=wrap(index),delta=wrap(dest-wrap(motion.target)+2.5)-2.5;motion.target+=delta;lastRaw=dest;jumping.current=true;el!.scrollTo({top:(dest+1)*unit,behavior:'instant'});jumping.current=false;wake()};
 function onScroll(){if(jumping.current)return;let raw=el!.scrollTop/unit-1;if(raw>=5){raw-=5;jumping.current=true;el!.scrollTop-=5*unit;jumping.current=false}else if(raw<0){raw+=5;jumping.current=true;el!.scrollTop+=5*unit;jumping.current=false}let delta=raw-lastRaw;if(delta>2.5)delta-=5;if(delta< -2.5)delta+=5;motion.target+=delta;lastRaw=raw;wake()}
 const onPointer=(e:PointerEvent)=>{if(settings.current.reduced||e.pointerType==='touch')return;const r=outer!.getBoundingClientRect();px=(e.clientX-r.left)/r.width*2-1;py=1-(e.clientY-r.top)/r.height*2;wake()},leave=()=>{px=py=0;wake()};const observer=new ResizeObserver(resize);observer.observe(el);resize();el.addEventListener('scroll',onScroll,{passive:true});outer.addEventListener('pointermove',onPointer,{passive:true});outer.addEventListener('pointerleave',leave);document.addEventListener('visibilitychange',wake);
 return()=>{observer.disconnect();cancelAnimationFrame(raf);el.removeEventListener('scroll',onScroll);outer.removeEventListener('pointermove',onPointer);outer.removeEventListener('pointerleave',leave);document.removeEventListener('visibilitychange',wake);motion.invalidate=()=>{}};
 },[motion]);
 useEffect(()=>{wakeRef.current()},[paused,pair,reduced,override]);
 function go(index:number){navigateRef.current(index)}
 function reveal(p:Project){setOverride(p);setPlaying(true);wakeRef.current()}
 const world=worlds[chapter],project=override||projects.find(p=>p.id===world.film)||projects[0],egg=projects.find(p=>p.id===world.egg)||project;
 return <div className="journey" ref={root} data-theme={world.kind} data-graphics={graphics?'auto':'compatible'}><div className="journey-scroll" ref={scroll} tabIndex={0} aria-label="Scroll to travel through five art worlds" role="region" onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(chapter+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(chapter-1)}}} style={{overflowY:paused?'hidden':'auto'}}><div className="journey-track"><div className="journey-stage">
 <div className="world-backgrounds" aria-hidden="true">{pair.map(i=><div key={i} className={'journey-world world-'+worlds[i].kind} data-world-index={i}><div className="world-atmosphere"/></div>)}</div>
 {graphics&&!reduced&&<GeometryBoundary onFailure={()=>setGraphics(false)}><Suspense fallback={null}><Scene motion={motion} onDiscover={()=>reveal(egg)} onFailure={()=>setGraphics(false)}/></Suspense></GeometryBoundary>}
 {!graphics&&<div className="compatible-geometry" aria-hidden="true"><div className="compatible-cube">{Array.from({length:6},(_,i)=><i key={i}/>)}</div><div className="compatible-ring"/></div>}
 {pair.map(i=><World key={i} index={i} projects={projects} onReveal={p=>p.provider==='youtube'?reveal(p):onProject(p)}/>)}
 <div className={'journey-screen '+((project.aspect||16/9)<1?'portrait-screen':'landscape-screen')} ref={screen} style={{'--film-ratio':project.aspect||16/9} as CSSProperties}>{world.kind==='desktop'&&<div className="retro-titlebar"><span>{project.title}</span><span aria-hidden="true">_ □ ×</span></div>}<div className="screen-shell">{!paused&&<JourneyPlayer project={project} enabled={!reduced&&!saveData} muted={muted} playing={playing} onOpen={()=>onProject(project)}/>}</div><div className="film-caption"><span>{project.title.split(' | ')[0].split(' (Official')[0]}</span><button onClick={()=>onProject(project)} aria-label="Project details">↗</button></div></div>
 <div className="journey-ui"><div className="journey-top"><span className="world-index">{String(chapter+1).padStart(2,'0')} <i>/</i> {world.name}</span><button className="journey-work" onClick={onIndex}>All work <span>↗</span></button></div><Discovery key={world.kind} project={egg} kind={world.icon} onReveal={reveal}/><div className="journey-bottom"><div className="journey-media-controls"><button aria-pressed={!muted} onClick={()=>setMuted(!muted)}>{muted?'Sound off':'Sound on'}</button><button aria-pressed={!playing} onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><button className="quality-control" aria-pressed={low} onClick={()=>{setLow(!low);motion.low=!low;wakeRef.current()}}>{low?'Eco':'Quality'}</button></div><nav className="world-navigation" aria-label="Art worlds"><button aria-label="Previous world" onClick={()=>go(chapter-1)}>←</button>{worlds.map((w,i)=><button key={w.kind} aria-label={w.name+' world'} aria-current={chapter===i?'step':undefined} onClick={()=>go(i)}><span>{String(i+1).padStart(2,'0')}</span><span className="nav-world-name">{w.name}</span></button>)}<button aria-label="Next world" onClick={()=>go(chapter+1)}>→</button></nav><span className="journey-scroll-cue">Scroll to drift <span>↓</span></span></div></div>
 </div></div></div></div>;
}
